[tool.poetry]
name = "imagebind"
version = "0.1.0"
description = ""
authors = ["Тимофей Пискленов"]
license = "MIT"
readme = "README.md"
packages = [{ include = "imagebind" }]  # Убедитесь, что здесь указан путь до внутренней папки

[tool.poetry.dependencies]
python = "^3.12"
alembic = "^1.11.3"
loguru = "^0.7.0"
ruff = "^0.3.7"
pre-commit = "^3.7.0"
asyncpg = "^0.29.0"
torch = "^2.4.1"
torchvision = "^0.19.1"
einops = "^0.8.0"
regex = "^2024.9.11"
timm = "^1.0.9"
iopath = "^0.1.10"
ftfy = "^6.2.3"
torchaudio = "^2.4.1"
pytorchvideo = "^0.1.5"
moviepy = "^1.0.3"
transformers = "^4.45.1"
scikit-learn = "^1.5.2"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
exclude = ["models/__init__.py"]